### PUT request to update patient
PUT http://localhost:4000/patients/fafb2f7c-e138-46ef-9c09-14e3fdd8e2d9
Content-Type: application/json

{
  "name":"Shashini Madushika",
  "email":"shashinimaduu@gmail.com",
  "address":"Colombo",
  "dateOfBirth":"1999-10-20"
}
###