### PUT request to update patient
PUT http://localhost:4000/patients/5997057e-8bd3-4c69-a3b2-ddc7a0ac55a6
Content-Type: application/json

{
  "name":"Shashini Madushika",
  "email":"shashinimaduu@gmail.com",
  "address":"Colombo",
  "dateOfBirth":"1999-10-20"
}
###